### ISSUE TITLE
What's the difference between Question and Poll?

### ISSUE THREAD

**Issue by jgorset** [hyperoslo/tasuku#71]
I'm just looking at the structure of things now and I can't seem to find any good reason we have both a model [`Question`](https://github.com/hyperoslo/tasuku/blob/master/lib/tasuku/concerns/models/taskables/question.rb) and [`Poll`](https://github.com/hyperoslo/tasuku/blob/master/lib/tasuku/concerns/models/taskables/poll.rb). They seem exactly the same to me. Why did we do this again, @sindrenm?

**Comment by mathiasbno** [comment]
Looks like no difference at all ![Nothing at all](http://i.imgur.com/aBWVo4u.gif)

And I just tested it in an app, they looked and behaved exactly the same.

:cactus: :fallen_leaf:

**Comment by timkurvers** [comment]
https://github.com/hyperoslo/tasuku/pull/62

**Comment by sindrenm** [comment]
They are semantically different, and also questions require people to answer correct, where a poll is “always correct”.

**Comment by jgorset** [comment]
I don't know, something about it just rubs me the wrong way – looking over #62 again, should we rather have introduced a property to derive whether _all_ or _one_ option must be correct in order for your answer to be considered correct overall?

**Comment by sindrenm** [comment]
**rubs**, courtesy of @timkurvers.

**Comment by timkurvers** [comment]
:open_mouth:

**Comment by jgorset** [comment]
Hi old friends! I'm cleaning up my issues, so I'm closing this one. Trust you won't mind. :blush:
